spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/openelifba}
    username: ${DB_USER:openelifba}
    password: ${DB_PASSWORD:openelifba}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jooq:
    sql-dialect: POSTGRES
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.zaxxer.hikari: DEBUG
    org.postgresql: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
